### ISSUE TITLE
Ubuntu 14.10 - Capture selection

### ISSUE THREAD

**Issue by laszlo-karpati** [olav-st/screencloud#106]
Can't use the "capture selection" function on Ubutunu 14.10 (see the sceenshot).

ver: 1.1.6.

![screenshot from 2014-10-14 17 13 00](https://cloud.githubusercontent.com/assets/4202290/4631317/aaff6818-53b4-11e4-8917-4babb2d129cb.png)

**Comment by lastk** [comment]
I cant fix it, so I'll wait to someone with a good heart and skills fix it asap ! :)

**Comment by nikolov-tmw** [comment]
Thought I'd share: when I have an external monitor plugged-in(I'm using a laptop), the capture selection works just fine.

**Comment by nikolov-tmw** [comment]
Grabbing a selection via the terminal works. The following:
``screencloud -c --service sftp --area 0,0,200,200``

Produces this image: 
http://screens.paiyakdev.com/Screenshot-at-2015-01-25_00:31:35.png 

Which is fine. So the issue is somewhere within the GUI tool that grabs the selection. Not sure what it's internal process is, but I assume that it's creating a new window and placing the screen dump in it. It does happen even when the launcher is hidden(then it only happens vertically, from the top bar).

Not sure how else to debug this issue.

**Comment by excieve** [comment]
Similar issue on Fedora 21 with GNOME 3.14. Odd enough, at times it works fine but mostly not.
![screenshot at 12-14-41](https://cloud.githubusercontent.com/assets/1077193/7366331/364536d4-eda0-11e4-860b-9ef57112cf90.png)

**Comment by excieve** [comment]
Here's a screencast of how it looks during the capture selection if this helps. Apparently something doesn't work right with the overlay window:
https://www.dropbox.com/s/w6pxp0vy3ixk1s0/Screencast_05.05.15_12%3A58%3A18.webm?dl=0
