### ISSUE TITLE
[Archlinux] Incompatible ssh peer (no acceptable kex algorithm)

### ISSUE THREAD

**Issue by modInfo** [olav-st/screencloud#108]
It does not work uploading on the sftp server, this was my favorite feature.

At 2 weeks did not work Capture Selection, today I made the update* from github now work Capture Selection but it does not work uploading...

```
Upload failed!
Error while connecting to example.com:22. Incompatible ssh peer (no acceptable kex algorithm)
```
*update = yaourt -R screencloud; yaourt -S screencloud-git

**Comment by zingmars** [comment]
Not just an Arch issue. Happens to me as well (client - Linux Mint, server - Gentoo). Seems to be an issue with ScreenCloud using an older version of Paramiko?

**Comment by zingmars** [comment]
After looking around a bit, I found out that the sftp plugin comes with it's own paramiko library that's quite out of date.  It can be found here -
~/.local/share/data/screencloud/ScreenCloud/plugins/sftp/modules

Until the devs update the plugin themselves, the fix is to download paramiko from their github page at https://github.com/paramiko/paramiko, and copying the paramiko folder over the sftp plugin's one.

**Comment by modInfo** [comment]
@zingmars thank you so much! 
My favorite program works through you.  
Test: http://i.img.itunix.eu/2015-01-04-03:45:05.png
