### ISSUE TITLE
Area selector doesn't work in Gnome Shell

### ISSUE THREAD

**Issue by tomslominski** [olav-st/screencloud#14]
Hi. The title pretty much says it all. I have installed the [Appindicator support](https://extensions.gnome.org/extension/615/appindicator-support/) extension, so I have screencloud in my top bar. Capturing the whole screen and a single window works well, and both get a notification at the bottom, which is good. However, selecting an area to screenshot doesn't work. Sometimes the overlay flashes for a split second, but usually nothing happens at all.

**Comment by DoctorJellyface** [comment]
1.2 here, GNOME 3.14, Arch Linux. The issue was, but disappeared.

However, if I press "Capture Selection", and start playing with another window before the overlay comes up, it doesn't get focus. You can see it, but the top bar is above it, and you can't interact with it with the keyboard before you click on it. Quite confusing since at start you can't close it with Escape.
