### ISSUE TITLE
Dependency issue on kubuntu 15.04

### ISSUE THREAD

**Issue by atjensw** [olav-st/screencloud#144]
Selecting previously unselected package screencloud.
(Reading database ... 137309 files and directories currently installed.)
Preparing to unpack screencloud_1.2.0-1_amd64.deb ...
Unpacking screencloud (1.2.0-1) ...
dpkg: dependency problems prevent configuration of screencloud:
 screencloud depends on libqtmultimediakit1; however:
  Package libqtmultimediakit1 is not installed.
 screencloud depends on libqxt-core0; however:
  Package libqxt-core0 is not installed.
 screencloud depends on libqxt-gui0; however:
  Package libqxt-gui0 is not installed.
 screencloud depends on libquazip0; however:
  Package libquazip0 is not installed.

dpkg: error processing package screencloud (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.14-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for mime-support (3.58ubuntu1) ...
Errors were encountered while processing:
 screencloud

**Comment by Trucido** [comment]
Dependencies need to be updated to libquazip1 instead of libquazip0

you can install screencloud on 15.04 based distros by symlinking libquazip1 to libquazip0

$ wget http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_14.04/amd64/screencloud_1.2.0-1_amd64.deb
$ sudo apt-get install –no-install-recommends libqtmultimediakit1 libqxt-core0 libqxt-gui0 libquazip1
$ sudo ln -s /usr/lib/x86_64-linux-gnu/libquazip.so.1.0.0 /usr/lib/x86_64-linux-gnu/libquazip.so.0
$sudo dpkg -i –force-depends screencloud_1.2.0-1_amd64.deb

**Comment by atjensw** [comment]
Thanks, it didn't worked thou, but if i changed the last line in you guide to: sudo dpkg -i --ignore-depends=libquazip0 screencloud_1.2.0-1_amd64.deb it got installed and it seems to work.

**Comment by Trucido** [comment]
hmm I did the last command as root, maybe --force-depends doesn't work through sudo. glad you got it working though, but they really do need to fix this depdendency issue and/or make an updated package for 15.04 based distros

**Comment by pfoo** [comment]
I think this bug can be closed, as latest package from repo (http://download.opensuse.org/repositories/home:/olav-st/xUbuntu_14.04/) has libquazip1 as depency.
Depends: libc6, libgcc1, libstdc++6, libqt4-designer (>= 4:4.5.3), libqt4-network (>= 4:4.5.3), libqt4-xml (>= 4:4.5.3), libqt4-svg (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.8.0), libqtmultimediakit1, libqxt-core0, libqxt-gui0, libquazip0 | libquazip1, libpython2.7
