### ISSUE TITLE
Segmentation fault on Arch installation

### ISSUE THREAD

**Issue by billyhicks** [olav-st/screencloud#205]
I installed the 64 bit package using Pacman. The programme opens but then segfaults with the following error message
`/usr/bin/screencloud: line 13: 16198 Segmentation fault      (core dumped) LD_LIBRARY_PATH=/opt/screencloud /opt/screencloud/screencloud "$@"
`

**Comment by billyhicks** [comment]
Running debug I get the following

`[INFO] "Loaded 0 plugin(s)"
PulseAudioService: pa_context_connect() failed
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg"
[WARN] "sfx/shutter.wav does not exist."
Segmentation fault (core dumped)
`
Not too sure why pulseaudio is being invoked? Or why shutter.wav is necessary.

**Comment by AlfredoRamos** [comment]
`screencloud` is not in any of the official repositories so it can't be installed with `pacman`, contact the maintainer of the AUR package.

PS: PulseAudio in called to play that `*.wav` sound, is not required, that's why It only shows a warning.

**Comment by 5shekel** [comment]
im still getting this, whats the solution?
downgrade to pythonQt 3.0 ?

**Comment by AlfredoRamos** [comment]
@5shekel It currently works just fine with PythonQt 3.1, so this issue has been fixed, at least in the AUR packages.

The one that can be installed adding a custom repository <sup>[[ref1]]</sup> needs to be updated <sup>[[ref2]]</sup>], because the PKGBUILD <sup>[[ref3]]</sup> uses two dependencies (`quazip-qt5` and `pythonqt-qt5`) that don't exist.

The path was changed in commit 3ac0cb9 so you should do a clean install, you'll need to remove these directories before building the package.

```
~/.local/share/screencloud
~/.config/screencloud
```
[ref1]: https://software.opensuse.org/download.html?project=home%3Aolav-st&package=screencloud
[ref2]: https://build.opensuse.org/project/monitor/home:olav-st?blocked=0&building=0&dispatching=0&finished=0&pkgname=screencloud&scheduled=0&signing=0&succeeded=0
[ref3]: https://build.opensuse.org/package/view_file/home:olav-st/screencloud/PKGBUILD?expand=1

**Comment by 5shekel** [comment]
this worked for me, thankx

    yaourt -Rs screencloud
    rm -fr ~/.local/share/screencloud
    rm -fr ~/.config/screencloud
    yaourt screencloud
