### ISSUE TITLE
Screencloud doing absolutly nothing

### ISSUE THREAD

**Issue by zeparu** [olav-st/screencloud#220]
when i start it, it wont open, well it opens kinda, but it's stuck,
the terminal says this:

```
$ screencloud
[INFO] "Loaded 0 plugin(s)"
[INFO] "Using bundled icon: :/systray/trayicon-gray.svg"
```

after that i can't even close the command with ctrl+c, it just shows up as ^C
i already tried purging screencloud and reinstalling it, still won't work rip

**Comment by olav-st** [comment]
Which distro, which verision of ScreenCloud?

**Comment by ZahnPastor** [comment]
Im using ubuntu 16.04, and the newest version of screencloud, the update from yesterday, i installed it via the ppa

**Comment by harkor** [comment]
I have the same problem of fedora 23 last version of screencloud.

At the launch of screencloud : Script error in plugin 'ftp'
After I click on "ok" from the error box, I have another error in a box : "Failed to call FTPUploader.isConfigured()....."

If I click on ftp settings, same error.

**Comment by samlev** [comment]
Just updated from Ubuntu 14.04 to 16.04, and installed the latest version of screencloud through `apt` (I'll also note that Chrome 53 is refusing to show your site due to an outdated SSL cipher - I had to use firefox to get there). When booting screencloud from cli, it tells me the exact same messages that @ZahnPastor reported, and nothing shows up in sys tray.

It's a mild improvement over the python syntax errors thrown all over the 14.04 version, because while it still doesn't work, at least I don't have to click "ok" a bunch of times.
