### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by mainameiz** [olav-st/screencloud#340]
Hello, Olav!

I'm very excited of this software and would like to make a donation. Besides I see that http://screencloud.net does not work. Probably some people like me would help you to keep the project and its site up and running.

Would you like to use a platfrom for donations like http://www.patreon.com?

**Comment by cantalupo555** [comment]
I would like to make a donation to, keep this beautiful project in the working.

**Comment by olav-st** [comment]
Hi. Thanks for the excitement! :) 

I'll look into adding a donation option, but I'm not sure if patreon is the best option since I'm not actively maintaining the project (only when I have some free time).  As for the website, I'm currently working on moving it to github pages which hopefully will improve stability.

**Comment by xMase** [comment]
I don't know if financing a developer directly is correct when other developers of the open source community have devoted themselves to developing solutions to keep the project active.
