### ISSUE TITLE
Fullscreen screenshot not working correctly with 2 Monitors with same name. OSX

### ISSUE THREAD

**Issue by slohmaier** [olav-st/screencloud#35]
I have OSX and two monitors with the same name. That seems to confuse screencloud. 

The left part shows the right screen too. When in reality there is just a terminal with the bottom bar...

I put my monitor configuration in the screenshot.

![screenshot at 2014-01-26 14 23 02](https://f.cloud.github.com/assets/228552/2004003/45ffd2b2-868d-11e3-9519-32ba751127e6.png)

**Comment by Triplenox** [comment]
This issue is still occurring, currently using version 1.2.0 - essentially the same issue still occurs, on my right screen (actual iMac) it allows me to take a screenshot with no issues, however on my left screen (other monitor) if you haven't captured anything, it will display a grey background and then the "Draw a rectangular area".

However, if you have already captured something on the other screen - this will be the background and it will try to re-capture this again. Would love to see a fix for this.

**Comment by ghost1227** [comment]
Still happening...

**Comment by vegberg** [comment]
This still happens on ScreenCLoud 1.2.0 on Ubuntu 15.10

**Comment by Triplenox** [comment]
Doubt this is going to be fixed, issue has been ignored for years. I switched to Monosnap and it works fine, would recommend this over Screencloud any day.

**Comment by ZurMaD** [comment]
#379
