### ISSUE TITLE
Capture only ever captures the desktop

### ISSUE THREAD

**Issue by STVERLY** [olav-st/screencloud#380]
Windows version 1.5.2

Long time user, recently updated version, recently updated to new ftp destination.

Whatever I try to capture, the application is always hidden and I can only capture the desktop. Sounds like some kind of security 'I don't trust this app to capture my details' thing.

Any ideas?

**Comment by olav-st** [comment]
That's strange :thinking: Does it happen with all capture types (full screen, selection & window)?

**Comment by STVERLY** [comment]
Hi - yes it does - Full, Selection, Window :)
Steve

**Comment by payam124** [comment]
mine as well.
the only thing which I'm suspect it multiple active screens.
I have 4 displays. when I disabled one of them, it started to work fine

**Comment by olav-st** [comment]
Do you have "capture multiple monitors" enabled in the settings? And does it make a difference if you disable it?

**Comment by rikai** [comment]
Can confirm this as well. Updated to the latest version today. I have multiple active screens.

I actually managed to track down the source of the issue, and it seems to be due to a display arrangement issue. Messing around between the nvidia display settings and the windows display settings _does_ allow this to work as expected if you have the primary display be on the left, which for me is my right monitor (Monitor 2) like this:
![image](https://user-images.githubusercontent.com/515221/97124425-44aa3e00-16ed-11eb-9230-16d3de0e63be.png) and ![image](https://user-images.githubusercontent.com/515221/97124434-4ecc3c80-16ed-11eb-9642-9d1166dab38d.png) however, this is untenable as it's the opposite of my physical configuration.

So this seems to be an issue where Screencloud is assuming the primary monitor is the leftmost in a setup. How this looks in practice is that if you attempt to screenshot on the rightmost monitor, it will capture my left monitor, assuming that the leftmost is the primary, displaying the left monitor capture that on the right monitor and If I attempt to capture on my leftmost monitor, it will give me a black screen, presumably because the display arrangement has told it that the other monitor is to the left of the other, and captures a black screen because nothing is there.

**Comment by payam124** [comment]
another experience: I have 4 monitors in a row. one the leftmost, when I do capture selection, it shows a gray area. when I go to the second screen from the left and try to capture, I see windows from the screen on its left. the same happens to the other  2 screens.

**Comment by STVERLY** [comment]
Hi - and apologies for the slow follow-up.

Yes I use 2x monitors, the same setup as before I upgraded.
The rest of the options *looks* like they'll work - region, window, etc and it offers to capture either screen ...but only ever captures the desktop background image.

Seems to be working by the devastatingly low tech method of unplugging the VGA and plugging it back in again, then clicking Detect in Display > Settings

Steve

**Comment by rikai** [comment]
Would be cool to see it fixed
