### ISSUE TITLE
MacOS Ventura

### ISSUE THREAD

**Issue by akti-kh** [olav-st/screencloud#396]
Hello. Cannot use Screencloud on macos ventura. App dont start.
Do you will make support Ventura?
Thank you

**Comment by BlueSky-fur** [comment]
I honestly think this project is deprecated. 

Its a shame, i loved it.

**Comment by olav-st** [comment]
It is not deprecated per se, but I no longer have the time to actively work on it because of other obligations. I will however accept pull requests if anyone wants to contribute to the project. 

For this specific issue, I don't have a Mac that is capable of running MacOS Ventura (the only Mac I have is from 2012). So I would need someone else's help here. I will happily publish the files if someone manages to compile a working version.

**Comment by BlueSky-fur** [comment]
Gotcha, will take a look at it in a day

**Comment by olav-st** [comment]
Great! I would suggest taking a look at [this wiki page](https://github.com/olav-st/screencloud/wiki/COMPILING-ON-MAC-OS-X).  Another useful resource could be the [.travis.yml](https://github.com/olav-st/screencloud/blob/master/.travis.yml)  file. I was using Travis to compile all the previous versions. Unfortunately, it has been shut it down for open source projects, but the file might still be useful as a guide for how to compile the application.
